channels:
  - conda-forge

dependencies:
  - python=3.9
  - pip=22.1.2
  - pip:
      - robocorp>=1.0.0
      - robocorp-tasks>=3.0.0
      - rpaframework>=23.0.0
      - rpaframework-core>=10.0.0
      - rpaframework-email>=2.0.0
      - fastapi>=0.95.1
      - uvicorn>=0.22.0
      - jinja2>=3.1.2
      - pandas>=2.0.1
      - scikit-learn>=1.2.2
      - nltk>=3.8.1
      - spacy>=3.5.2
      - pydantic>=1.10.7
      - python-dotenv>=1.0.0
