version: '3.8'

services:
  # Email testing server
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Web interface port
      - "5000:80"
      # SMTP server port
      - "25:25"
      # IMAP server port (if needed)
      - "143:143"
    volumes:
      # Persistent data storage
      - smtp4dev-data:/smtp4dev
    environment:
      - SERVER_NAME=smtp4dev
      - SERVERTYPE=smtp
      - BasePath=/
      - TlsMode=StartTls
      - NumberOfMessagesToKeep=100
      - NumberOfSessionsToKeep=100
      # Uncomment to increase logging
      # - LOGLEVEL=Trace
      
  # ProjectCompass API Server
  projectcompass-api:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - smtp4dev
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - EMAIL_HOST=smtp4dev
      - EMAIL_PORT=25
      - EMAIL_USE_TLS=false
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./services:/app/services
      - ./agent_system:/app/agent_system
      - ./data:/app/data
    # Use simplified healthcheck that doesn't require curl
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  # ProjectCompass Frontend (React App)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - projectcompass-api
    # Set up a network alias for better connectivity
    networks:
      default:
        aliases:
          - frontend
    environment:
      # Use absolute URL with host.docker.internal to access API from React app
      - REACT_APP_API_URL=http://host.docker.internal:8000
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: projectcompass-network

volumes:
  smtp4dev-data:
