version: '3.8'

services:
  postgres_db:
    # Use an image that includes PostgreSQL and pgvector
    # You can pin a specific version like 'ankane/pgvector:pg16' for stability
    image: ankane/pgvector:latest
    container_name: postgres_with_pgvector # A custom name for the container
    environment:
      # Set PostgreSQL credentials and default database
      # IMPORTANT: Change these default values for production!
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: myvectordb
      # Optional: Define where PostgreSQL stores its data within the container
      # PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      # Map host port 5432 to container port 5432
      # Format: "HOST_PORT:CONTAINER_PORT"
      # Change the host port (left side) if 5432 is already in use on your machine
      - "5432:5432"
    volumes:
      # Mount a named volume to persist database data outside the container
      # This ensures your data survives container restarts and removals
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped # Restart policy: restart unless manually stopped
    # Optional Healthcheck: Checks if the database is ready to accept connections
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  # Email testing server
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Web interface port
      - "5000:80"
      # SMTP server port
      - "25:25"
      # IMAP server port (if needed)
      - "143:143"
    volumes:
      # Persistent data storage
      - smtp4dev-data:/smtp4dev
    environment:
      - SERVER_NAME=smtp4dev
      - SERVERTYPE=smtp
      - BasePath=/
      - TlsMode=StartTls
      - NumberOfMessagesToKeep=100
      - NumberOfSessionsToKeep=100
      # Uncomment to increase logging
      # - LOGLEVEL=Trace
      
  # ProjectCompass API Server
  projectcompass-api:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - smtp4dev
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - EMAIL_HOST=smtp4dev
      - EMAIL_PORT=25
      - EMAIL_USE_TLS=false
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./services:/app/services
      - ./agent_system:/app/agent_system
      - ./data:/app/data
    # Use simplified healthcheck that doesn't require curl
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  # ProjectCompass Frontend (React App)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - projectcompass-api
    # Set up a network alias for better connectivity
    networks:
      default:
        aliases:
          - frontend
    environment:
      # Use absolute URL with host.docker.internal to access API from React app
      - REACT_APP_API_URL=http://host.docker.internal:8000
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: projectcompass-network

volumes:
  # Define the named volume for persistent data storage
  postgres_data:
    driver: local # Specifies the volume driver (local is the default)
  smtp4dev-data:
